[2022-02-17 06:00:18,702] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: failMailTestEachTask_dag.test 2022-02-16T00:00:00+00:00 [queued]>
[2022-02-17 06:00:18,718] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: failMailTestEachTask_dag.test 2022-02-16T00:00:00+00:00 [queued]>
[2022-02-17 06:00:18,719] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 06:00:18,719] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2022-02-17 06:00:18,719] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 06:00:18,731] {__init__.py:1374} INFO - Executing <Task(BashOperator): test> on 2022-02-16T00:00:00+00:00
[2022-02-17 06:00:18,731] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'failMailTestEachTask_dag', 'test', '2022-02-16T00:00:00+00:00', '--job_id', '121', '--raw', '-sd', 'DAGS_FOLDER/failMailTestEachTask.py', '--cfg_path', '/tmp/tmpela6s0ah']
[2022-02-17 06:00:19,197] {base_task_runner.py:101} INFO - Job 121: Subtask test [2022-02-17 06:00:19,196] {__init__.py:51} INFO - Using executor SequentialExecutor
[2022-02-17 06:00:19,393] {base_task_runner.py:101} INFO - Job 121: Subtask test [2022-02-17 06:00:19,393] {__init__.py:305} INFO - Filling up the DagBag from /home/jovyan/airflow/dags/failMailTestEachTask.py
[2022-02-17 06:00:19,403] {base_task_runner.py:101} INFO - Job 121: Subtask test [2022-02-17 06:00:19,403] {cli.py:517} INFO - Running <TaskInstance: failMailTestEachTask_dag.test 2022-02-16T00:00:00+00:00 [running]> on host 4c5aeb1c47d1
[2022-02-17 06:00:19,415] {bash_operator.py:81} INFO - Tmp dir root location: 
 /tmp
[2022-02-17 06:00:19,415] {bash_operator.py:90} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=failMailTestEachTask_dag
AIRFLOW_CTX_TASK_ID=test
AIRFLOW_CTX_EXECUTION_DATE=2022-02-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-16T00:00:00+00:00
[2022-02-17 06:00:19,416] {bash_operator.py:104} INFO - Temporary script location: /tmp/airflowtmp1lzc8zni/testre4skmg6
[2022-02-17 06:00:19,416] {bash_operator.py:114} INFO - Running command: exit(1)
[2022-02-17 06:00:19,422] {bash_operator.py:123} INFO - Output:
[2022-02-17 06:00:19,423] {bash_operator.py:127} INFO - /tmp/airflowtmp1lzc8zni/testre4skmg6: line 1: syntax error near unexpected token `1'
[2022-02-17 06:00:19,423] {bash_operator.py:127} INFO - /tmp/airflowtmp1lzc8zni/testre4skmg6: line 1: `exit(1)'
[2022-02-17 06:00:19,423] {bash_operator.py:131} INFO - Command exited with return code 2
[2022-02-17 06:00:19,426] {__init__.py:1580} ERROR - Bash command failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/conda/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-02-17 06:00:19,427] {__init__.py:1611} INFO - Marking task as FAILED.
[2022-02-17 06:00:19,623] {logging_mixin.py:95} INFO - [2022-02-17 06:00:19,622] {email.py:126} INFO - Sent an alert email to ['sondonghyun7@hyundai.com']
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test Traceback (most recent call last):
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test   File "/opt/conda/bin/airflow", line 32, in <module>
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test     args.func(args)
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test     return f(*args, **kwargs)
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test     _run(args, dag, ti)
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test     pool=args.pool,
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test     return func(*args, **kwargs)
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test     result = task_copy.execute(context=context)
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test     raise AirflowException("Bash command failed")
[2022-02-17 06:00:19,803] {base_task_runner.py:101} INFO - Job 121: Subtask test airflow.exceptions.AirflowException: Bash command failed
[2022-02-17 06:00:23,693] {logging_mixin.py:95} INFO - [2022-02-17 06:00:23,692] {jobs.py:2562} INFO - Task exited with return code 1
