[2022-02-15 08:00:49,775] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: my_first_dag.send_email 2022-02-14T00:00:00+00:00 [queued]>
[2022-02-15 08:00:49,779] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: my_first_dag.send_email 2022-02-14T00:00:00+00:00 [queued]>
[2022-02-15 08:00:49,779] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 08:00:49,779] {__init__.py:1354} INFO - Starting attempt 9 of 9
[2022-02-15 08:00:49,779] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2022-02-15 08:00:49,788] {__init__.py:1374} INFO - Executing <Task(EmailOperator): send_email> on 2022-02-14T00:00:00+00:00
[2022-02-15 08:00:49,788] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'my_first_dag', 'send_email', '2022-02-14T00:00:00+00:00', '--job_id', '22', '--raw', '-sd', 'DAGS_FOLDER/my_first.py', '--cfg_path', '/tmp/tmph4u8d_vg']
[2022-02-15 08:00:50,191] {base_task_runner.py:101} INFO - Job 22: Subtask send_email [2022-02-15 08:00:50,191] {__init__.py:51} INFO - Using executor SequentialExecutor
[2022-02-15 08:00:50,344] {base_task_runner.py:101} INFO - Job 22: Subtask send_email [2022-02-15 08:00:50,344] {__init__.py:305} INFO - Filling up the DagBag from /home/jovyan/airflow/dags/my_first.py
[2022-02-15 08:00:50,356] {base_task_runner.py:101} INFO - Job 22: Subtask send_email [2022-02-15 08:00:50,355] {cli.py:517} INFO - Running <TaskInstance: my_first_dag.send_email 2022-02-14T00:00:00+00:00 [running]> on host 4c5aeb1c47d1
[2022-02-15 08:00:52,550] {__init__.py:1580} ERROR - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h5sm40094798pfi.111 - gsmtp')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/conda/lib/python3.7/site-packages/airflow/operators/email_operator.py", line 78, in execute
    mime_subtype=self.mime_subtype, mime_charset=self.mime_charset)
  File "/opt/conda/lib/python3.7/site-packages/airflow/utils/email.py", line 55, in send_email
    mime_subtype=mime_subtype, mime_charset=mime_charset, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/airflow/utils/email.py", line 101, in send_email_smtp
    send_MIME_email(smtp_mail_from, recipients, msg, dryrun)
  File "/opt/conda/lib/python3.7/site-packages/airflow/utils/email.py", line 125, in send_MIME_email
    s.login(SMTP_USER, SMTP_PASSWORD)
  File "/opt/conda/lib/python3.7/smtplib.py", line 735, in login
    raise last_exception
  File "/opt/conda/lib/python3.7/smtplib.py", line 726, in login
    initial_response_ok=initial_response_ok)
  File "/opt/conda/lib/python3.7/smtplib.py", line 647, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h5sm40094798pfi.111 - gsmtp')
[2022-02-15 08:00:52,551] {__init__.py:1611} INFO - Marking task as FAILED.
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email Traceback (most recent call last):
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/bin/airflow", line 32, in <module>
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     args.func(args)
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     return f(*args, **kwargs)
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     _run(args, dag, ti)
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     pool=args.pool,
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     return func(*args, **kwargs)
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     result = task_copy.execute(context=context)
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/operators/email_operator.py", line 78, in execute
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     mime_subtype=self.mime_subtype, mime_charset=self.mime_charset)
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/email.py", line 55, in send_email
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     mime_subtype=mime_subtype, mime_charset=mime_charset, **kwargs)
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/email.py", line 101, in send_email_smtp
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     send_MIME_email(smtp_mail_from, recipients, msg, dryrun)
[2022-02-15 08:00:52,563] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/email.py", line 125, in send_MIME_email
[2022-02-15 08:00:52,564] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     s.login(SMTP_USER, SMTP_PASSWORD)
[2022-02-15 08:00:52,564] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/smtplib.py", line 735, in login
[2022-02-15 08:00:52,564] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     raise last_exception
[2022-02-15 08:00:52,564] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/smtplib.py", line 726, in login
[2022-02-15 08:00:52,564] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     initial_response_ok=initial_response_ok)
[2022-02-15 08:00:52,564] {base_task_runner.py:101} INFO - Job 22: Subtask send_email   File "/opt/conda/lib/python3.7/smtplib.py", line 647, in auth
[2022-02-15 08:00:52,564] {base_task_runner.py:101} INFO - Job 22: Subtask send_email     raise SMTPAuthenticationError(code, resp)
[2022-02-15 08:00:52,564] {base_task_runner.py:101} INFO - Job 22: Subtask send_email smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h5sm40094798pfi.111 - gsmtp')
[2022-02-15 08:00:54,778] {logging_mixin.py:95} INFO - [2022-02-15 08:00:54,778] {jobs.py:2562} INFO - Task exited with return code 1
